<?php

namespace Database\Seeders;

use App\Models\Saint;
use Illuminate\Database\Seeder;

class SaintSeeder extends Seeder
{
    public function run(): void
    {
        $saints = [
            [
                'name' => 'St. Pedro Calungsod',
                'feast_month' => 4,
                'feast_day' => 2,
                'title' => 'Young Filipino Catechist and Martyr',
                'short_story' => 'St. Pedro Calungsod was a young Filipino catechist who helped share the Catholic faith and witnessed to Christ with courage.',
                'full_story' => 'St. Pedro Calungsod was a young Filipino catechist and missionary who gave his life while sharing the Catholic faith. He served with Jesuit missionaries in Guam and helped teach the Gospel with patience and devotion. Even in hardship, he remained faithful, showing courage without bitterness. The Church remembers him as a witness that holiness is possible for the young, the simple, and the willing. His life invites us to stay faithful to Christ, to serve others with generosity, and to trust God in moments that ask for sacrifice. He is a powerful example of courage, fidelity, and missionary love.',
                'virtue' => 'Courage and Faithfulness',
                'life_lesson' => 'Faithfulness means following Christ even when it is difficult.',
                'prayer' => 'St. Pedro Calungsod, pray for us and help us live with courage and faithfulness.',
                'image_path' => 'assets/images/saints/st_pedro_calungsod.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'St. Joseph',
                'feast_month' => 3,
                'feast_day' => 19,
                'title' => 'Spouse of the Blessed Virgin Mary',
                'short_story' => 'The foster father of Jesus is remembered for his quiet obedience and faithful care.',
                'full_story' => 'St. Joseph is honored as the spouse of Mary and the foster father of Jesus. The Gospels show him as a man of deep faith who listened to God and acted quickly. He protected the Holy Family, provided for them through humble work, and accepted tasks that were hidden from public view. Joseph did not seek attention, but his obedience made room for God\'s plan to unfold. He is a model for fathers, workers, and anyone who wants to serve the Lord quietly and faithfully. His life teaches that holiness is often found in simple trust and steady responsibility.',
                'virtue' => 'Obedience',
                'life_lesson' => 'Holiness is often lived through faithful hidden service.',
                'prayer' => 'St. Joseph, guide our families and our work.',
                'image_path' => 'assets/images/saints/st_joseph.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'The Annunciation of the Lord',
                'feast_month' => 3,
                'feast_day' => 25,
                'title' => 'Solemnity',
                'short_story' => 'The Church remembers Mary\'s yes to God and the beginning of the Incarnation.',
                'full_story' => 'The Annunciation celebrates the moment when the angel Gabriel announced God\'s plan to Mary. Her humble yes opened the way for the Incarnation, when the Son of God became man. This feast reminds the Church that God often works through quiet faith, openness, and trust. Mary did not have every answer, but she offered her life to God with confidence. Her response still teaches Christians how to listen, surrender, and receive grace. The Annunciation is a joyful reminder that salvation begins with God\'s initiative and a willing heart.',
                'virtue' => 'Trust',
                'life_lesson' => 'God can do great things through a willing yes.',
                'prayer' => 'Lord, give us the grace to say yes to your will.',
                'image_path' => 'assets/images/saints/annunciation_of_the_lord.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'St. Mark the Evangelist',
                'feast_month' => 4,
                'feast_day' => 25,
                'title' => 'Evangelist',
                'short_story' => 'Tradition remembers Mark as a companion of the apostles and a faithful witness of the Gospel.',
                'full_story' => 'St. Mark is traditionally remembered as the author of the second Gospel and a companion in the apostolic mission. His Gospel presents Jesus with urgency, clarity, and power, helping believers focus on Christ\'s saving work. Mark\'s life is associated with preaching, service, and the growth of the early Church. He is a reminder that the Gospel is meant to be shared, not kept private. Through his witness, Christians are encouraged to speak about Jesus plainly and confidently. Mark\'s feast invites the Church to renew its love for the Word of God.',
                'virtue' => 'Witness',
                'life_lesson' => 'Sharing the Gospel helps the Church remember Christ clearly.',
                'prayer' => 'St. Mark, help us proclaim the Gospel with courage.',
                'image_path' => 'assets/images/saints/st_mark_the_evangelist.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'St. Philip Neri',
                'feast_month' => 5,
                'feast_day' => 26,
                'title' => 'Priest',
                'short_story' => 'A joyful priest known for prayer, friendship, and gentle evangelization.',
                'full_story' => 'St. Philip Neri was a joyful priest who brought people to God through prayer, friendship, and humor. In the busy life of Rome, he welcomed many into a deeper relationship with Christ by combining seriousness about holiness with a light and loving spirit. He founded the Congregation of the Oratory and devoted his life to confession, spiritual direction, and encouraging ordinary people. Philip showed that evangelization does not always need force; sometimes joy and kindness open the heart best. He remains a beloved guide for anyone who wants to serve God with warmth and freedom.',
                'virtue' => 'Joy',
                'life_lesson' => 'A joyful heart can draw others to God.',
                'prayer' => 'St. Philip Neri, teach us holy joy.',
                'image_path' => 'assets/images/saints/st_philip_neri.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'St. Augustine of Canterbury',
                'feast_month' => 5,
                'feast_day' => 27,
                'title' => 'Missionary Bishop',
                'short_story' => 'Sent to evangelize England, he helped plant and strengthen the Church there.',
                'full_story' => 'St. Augustine of Canterbury was sent from Rome to evangelize England and became the first Archbishop of Canterbury. His mission was not easy, but he remained faithful to the call of Christ and helped establish the Church in a new land. Augustine worked to preach the Gospel, organize worship, and form Christian communities that could grow over time. His story reminds us that mission often requires patience, courage, and trust in God\'s timing. He is a witness that the Church grows when people are willing to go where they are needed.',
                'virtue' => 'Missionary Zeal',
                'life_lesson' => 'The Gospel grows when people are willing to be sent.',
                'prayer' => 'St. Augustine of Canterbury, make us ready to be sent by Christ.',
                'image_path' => 'assets/images/saints/st_augustine_of_canterbury.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'Visitation of the Blessed Virgin Mary',
                'feast_month' => 5,
                'feast_day' => 31,
                'title' => 'Feast',
                'short_story' => 'Mary visits Elizabeth, and both women praise God for his saving work.',
                'full_story' => 'The Visitation celebrates Mary\'s journey to visit her cousin Elizabeth after receiving the news of the Incarnation. In their meeting, both women rejoice in God\'s work and proclaim his mercy. Mary\'s presence brings joy, service, and praise. This feast teaches that Christian love is not passive; it moves toward others with care. Mary becomes a model of joyful service and humble charity. The Visitation invites believers to carry Christ to the people around them with kindness, humility, and gratitude.',
                'virtue' => 'Charity',
                'life_lesson' => 'Love often moves us to serve others quickly and humbly.',
                'prayer' => 'Mary, help us bring Christ to others with love.',
                'image_path' => 'assets/images/saints/visitation_of_the_blessed_virgin_mary.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'Sts. Peter and Paul',
                'feast_month' => 6,
                'feast_day' => 29,
                'title' => 'Apostles',
                'short_story' => 'Two great apostles whose preaching and witness helped shape the early Church.',
                'full_story' => 'Sts. Peter and Paul are honored together because their witness helped shape the life of the early Church. Peter was chosen as a shepherd for the disciples, while Paul became a tireless missionary and teacher to the nations. They were different men with different journeys, but both gave their lives for Christ. Their feast reminds the Church that unity does not require sameness; it requires faithfulness to the same Lord. Together they encourage believers to stay rooted in the apostolic faith and to proclaim the Gospel with courage.',
                'virtue' => 'Apostolic Faith',
                'life_lesson' => 'God can use different people for one mission.',
                'prayer' => 'Sts. Peter and Paul, strengthen the Church in faith.',
                'image_path' => 'assets/images/saints/sts_peter_and_paul.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'St. Ignatius of Loyola',
                'feast_month' => 7,
                'feast_day' => 31,
                'title' => 'Priest and Founder',
                'short_story' => 'Founder of the Jesuits, he taught discernment and deeper surrender to God.',
                'full_story' => 'St. Ignatius of Loyola began as a soldier, but a long recovery after battle changed his life. Through prayer and reflection, he discovered that Christ was calling him to something far greater. Ignatius founded the Society of Jesus and became a great teacher of discernment, helping people learn how to choose what leads them closer to God. His spiritual exercises remain deeply influential in the Church. Ignatius teaches that conversion is possible, that decisions matter, and that a surrendered heart can become a powerful instrument of grace.',
                'virtue' => 'Discernment',
                'life_lesson' => 'A faithful heart learns to choose what leads closer to Christ.',
                'prayer' => 'St. Ignatius, teach us to discern God\'s will.',
                'image_path' => 'assets/images/saints/st_ignatius_of_loyola.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'St. Maximilian Kolbe',
                'feast_month' => 8,
                'feast_day' => 14,
                'title' => 'Priest and Martyr',
                'short_story' => 'St. Maximilian Kolbe offered his life in place of another prisoner and witnessed to sacrificial love.',
                'full_story' => 'St. Maximilian Kolbe was a Franciscan priest who loved the Virgin Mary and used modern media to spread the faith. During World War II, he was imprisoned in Auschwitz, where he offered his life in place of another man who had been chosen for death. His sacrifice showed the Church what self-giving love looks like in its most heroic form. Kolbe\'s witness reminds believers that courage can be expressed through mercy, and that love is stronger than fear. His life continues to inspire Christians to choose sacrifice, compassion, and fidelity to Christ.',
                'virtue' => 'Sacrificial Love',
                'life_lesson' => 'Love becomes heroic when it gives itself for others.',
                'prayer' => 'St. Maximilian Kolbe, pray for us and teach us self-giving love.',
                'image_path' => 'assets/images/saints/st_maximilian_kolbe.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'The Assumption of the Blessed Virgin Mary',
                'feast_month' => 8,
                'feast_day' => 15,
                'title' => 'Solemnity',
                'short_story' => 'The Church celebrates Mary being taken body and soul into heavenly glory.',
                'full_story' => 'The Assumption of the Blessed Virgin Mary is a joyful celebration of Mary\'s share in the glory of her Son. The Church proclaims that Mary was taken body and soul into heaven, showing the destiny prepared for those who remain faithful to God. This feast is not only about Mary; it also points to the hope offered to all believers. Her life shows that humility, obedience, and trust in God lead to glory. The Assumption invites Christians to look toward heaven with hope and to live faithfully in the present.',
                'virtue' => 'Hope',
                'life_lesson' => 'Mary points us toward the promise of eternal life.',
                'prayer' => 'Blessed Mother, pray for us and lead us to your Son.',
                'image_path' => 'assets/images/saints/assumption_of_the_blessed_virgin_mary.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'St. Monica',
                'feast_month' => 8,
                'feast_day' => 27,
                'title' => 'Mother of St. Augustine',
                'short_story' => 'St. Monica prayed faithfully for her son Augustine and is remembered for perseverance in prayer.',
                'full_story' => 'St. Monica is remembered for her unwavering prayer, especially for her son Augustine. She endured many years of sorrow and concern, but she never stopped trusting God to work in his life. Her tears and prayers were not wasted; Augustine eventually converted and became one of the Church\'s greatest teachers. Monica\'s life teaches that patient love and persistent prayer can bear fruit in God\'s time. She is a comforting example for parents, spouses, and anyone praying for a loved one who is still far from the faith.',
                'virtue' => 'Perseverance',
                'life_lesson' => 'Patient prayer can bear fruit over time.',
                'prayer' => 'St. Monica, pray for families and persistent prayer.',
                'image_path' => 'assets/images/saints/st_monica.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'St. Augustine',
                'feast_month' => 8,
                'feast_day' => 28,
                'title' => 'Bishop and Doctor of the Church',
                'short_story' => 'St. Augustine became one of the Church\'s great teachers after a long journey of conversion.',
                'full_story' => 'St. Augustine of Hippo is one of the greatest saints and teachers in Christian history. Before his conversion, he searched for truth in many places and lived with a restless heart. Through prayer, the witness of his mother Monica, and the grace of God, he came to embrace Christ fully. Augustine later became bishop of Hippo and wrote works that shaped theology and spirituality for centuries. His story reminds the Church that conversion can be deep and lasting, and that God can transform even a wandering life into a rich source of wisdom and holiness.',
                'virtue' => 'Conversion',
                'life_lesson' => 'God can transform even a restless heart into a faithful witness.',
                'prayer' => 'St. Augustine, help us seek truth and conversion of heart.',
                'image_path' => 'assets/images/saints/st_augustine.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'St. Francis of Assisi',
                'feast_month' => 10,
                'feast_day' => 4,
                'title' => 'Founder of the Franciscans',
                'short_story' => 'A humble saint who embraced poverty, peace, and love for all creation.',
                'full_story' => 'St. Francis of Assisi is loved for his radical simplicity, deep poverty, and joyful love for God\'s creation. After a dramatic conversion, he chose to live the Gospel with total freedom, serving the poor and calling others to peace. He founded the Franciscan family and became a sign of humility in the Church. Francis teaches that holiness can be beautiful, gentle, and full of joy. His life encourages believers to live simply, care for creation, and become instruments of peace in a divided world.',
                'virtue' => 'Humility',
                'life_lesson' => 'Joy grows where simplicity and trust in God are present.',
                'prayer' => 'St. Francis, make us instruments of peace.',
                'image_path' => 'assets/images/saints/st_francis_of_assisi.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'Our Lady of the Rosary',
                'feast_month' => 10,
                'feast_day' => 7,
                'title' => 'Marian Feast',
                'short_story' => 'The Church honors Mary under the title of Our Lady of the Rosary and the prayer she leads us to pray.',
                'full_story' => 'Our Lady of the Rosary reminds the Church of the power of praying with Mary while meditating on the life of Christ. The Rosary helps believers contemplate the mysteries of salvation with simplicity and devotion. This feast highlights Mary\'s maternal care and the way she leads the faithful closer to her Son. It invites families, children, and communities to pray together with confidence. The Rosary is both ancient and accessible, making it a treasured prayer for ordinary daily life and deep spiritual reflection.',
                'virtue' => 'Contemplation',
                'life_lesson' => 'The Rosary helps us reflect on the life of Christ with Mary.',
                'prayer' => 'Our Lady of the Rosary, pray for us.',
                'image_path' => 'assets/images/saints/our_lady_of_the_rosary.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'All Saints',
                'feast_month' => 11,
                'feast_day' => 1,
                'title' => 'Solemnity',
                'short_story' => 'The Church honors all saints, known and unknown, who now rejoice with God in heaven.',
                'full_story' => 'All Saints Day is the Church\'s celebration of every saint in heaven, both those we know by name and those known only to God. It reminds believers that holiness is not limited to a few famous figures. Rather, every baptized person is called to sainthood through grace, faith, and love. This solemnity fills the Church with hope, because the saints show that human life can be transformed by God. Their example encourages the faithful to pursue holiness in everyday life and to trust that heaven is the true home of those who love God.',
                'virtue' => 'Holiness',
                'life_lesson' => 'Every baptized person is called to holiness.',
                'prayer' => 'All Saints of God, pray for us.',
                'image_path' => 'assets/images/saints/all_saints.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'The Immaculate Conception',
                'feast_month' => 12,
                'feast_day' => 8,
                'title' => 'Solemnity',
                'short_story' => 'The Church celebrates Mary preserved from original sin by a unique grace of God.',
                'full_story' => 'The Immaculate Conception celebrates God\'s special grace given to Mary from the beginning of her life. Preserved from original sin, she was prepared to become the Mother of the Savior. This feast reveals both Mary\'s beauty and God\'s power to sanctify. It also reminds the Church that grace comes first and that God prepares people for the missions he gives them. The Immaculate Conception leads believers to thank God for Mary\'s holiness and to ask for purity of heart in their own lives.',
                'virtue' => 'Purity',
                'life_lesson' => 'God prepares hearts for the missions he gives them.',
                'prayer' => 'Mary, conceived without sin, pray for us.',
                'image_path' => 'assets/images/saints/immaculate_conception.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
            [
                'name' => 'St. Juan Diego',
                'feast_month' => 12,
                'feast_day' => 9,
                'title' => 'Visionary and Saint',
                'short_story' => 'St. Juan Diego received the apparition of Our Lady of Guadalupe and remained faithful to her message.',
                'full_story' => 'St. Juan Diego was a humble indigenous Christian from Mexico who encountered Our Lady of Guadalupe in 1531. Mary asked him to carry her message to the bishop, and through his obedience and perseverance, devotion to Guadalupe spread throughout the Americas. Juan Diego did not present himself as powerful or important, but God used his humility for a great mission. His life shows that the Lord entrusts important work to faithful hearts. He remains a beloved witness to simplicity, trust, and devotion to Mary and Jesus.',
                'virtue' => 'Humility',
                'life_lesson' => 'God entrusts important missions to humble and faithful hearts.',
                'prayer' => 'St. Juan Diego, pray for us and help us trust Mary\'s guidance.',
                'image_path' => 'assets/images/saints/st_juan_diego.png',
                'source_name' => 'Franciscan Media Saint of the Day',
                'source_url' => 'https://www.franciscanmedia.org/saint-of-the-day/',
            ],
            [
                'name' => 'The Nativity of the Lord',
                'feast_month' => 12,
                'feast_day' => 25,
                'title' => 'Solemnity',
                'short_story' => 'Christmas celebrates the birth of Jesus Christ, the Savior of the world.',
                'full_story' => 'The Nativity of the Lord is the celebration of Jesus\' birth in Bethlehem, when God entered human history in humility and love. In the manger, the Church sees the mystery of the Incarnation: the eternal Son of God becoming man for our salvation. Christmas is a feast of joy, peace, and wonder. It invites believers to receive Christ with the simplicity of shepherds and the devotion of Mary and Joseph. The Nativity reminds the world that God draws near not through power alone, but through love made flesh.',
                'virtue' => 'Joyful Wonder',
                'life_lesson' => 'God enters human life with humility and love.',
                'prayer' => 'Jesus, come and dwell among us.',
                'image_path' => 'assets/images/saints/the_nativity_of_the_lord.png',
                'source_name' => 'Vatican News / Catholic saint calendar reference',
                'source_url' => 'https://www.vaticannews.va/en/saints.html',
            ],
        ];

        foreach ($saints as $saint) {
            Saint::query()->updateOrCreate(
                [
                    'name' => $saint['name'],
                    'feast_month' => $saint['feast_month'],
                    'feast_day' => $saint['feast_day'],
                ],
                $saint
            );
        }
    }
}